#!/usr/bin/env python3
"""
Analysis script for global inference outputs.

Loads per-watershed windowed and reconstructed time series generated by
inference_global.py, computes metrics, and creates diagnostic plots.
"""

import argparse
import json
import os
from pathlib import Path
from typing import Dict, List, Optional, Sequence, Tuple, Union

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import yaml

from hydrology_metrics import calculate_hydrology_metrics


def get_experiment_config(config_path: str, experiment: Optional[str]):
    with open(config_path, "r") as file:
        full_config = yaml.safe_load(file)

    if experiment:
        if experiment not in full_config:
            available = [
                k for k in full_config.keys() if not k.startswith("base_") and k != "default_experiment"
            ]
            raise ValueError(f"Experiment '{experiment}' not found. Available: {available}")
        return full_config[experiment], experiment, full_config

    default_exp = full_config.get("default_experiment")
    if default_exp and default_exp in full_config:
        return full_config[default_exp], default_exp, full_config

    for key, value in full_config.items():
        if key.startswith("base_") or key == "default_experiment":
            continue
        return value, key, full_config

    raise ValueError("No experiments found in configuration file.")


def ensure_dir(path: str):
    os.makedirs(path, exist_ok=True)


def load_manifest(results_dir: str) -> Dict:
    manifest_path = os.path.join(results_dir, "results_manifest.json")
    if os.path.exists(manifest_path):
        with open(manifest_path, "r") as f:
            return json.load(f)
    return {}


def sanitize_name(name: str) -> str:
    return name.replace(" ", "_")


def load_dataframe(path: str, file_format: str) -> pd.DataFrame:
    if not os.path.exists(path):
        print(f"Warning: File not found {path}")
        return pd.DataFrame()
    if file_format == "csv":
        df = pd.read_csv(path)
    elif file_format == "parquet":
        df = pd.read_parquet(path)
    else:
        raise ValueError(f"Unsupported file format '{file_format}'")

    if "timestamp" in df.columns:
        df["timestamp"] = pd.to_datetime(df["timestamp"])
    return df


def empirical_cdf(values: np.ndarray) -> Tuple[np.ndarray, np.ndarray]:
    """Return sorted values and cumulative probabilities."""
    if values.size == 0:
        return np.array([]), np.array([])
    sorted_vals = np.sort(values)
    probs = np.arange(1, values.size + 1, dtype=np.float64) / values.size
    return sorted_vals, probs


def exceedance_curve(values: np.ndarray) -> Tuple[np.ndarray, np.ndarray]:
    """Return sorted values and exceedance probabilities P(X >= x)."""
    if values.size == 0:
        return np.array([]), np.array([])
    sorted_vals = np.sort(values)
    ranks = np.arange(1, values.size + 1, dtype=np.float64)
    exceedance = 1.0 - (ranks - 0.5) / values.size
    return sorted_vals, exceedance


def clean_pair(obs_series: pd.Series, pred_series: pd.Series) -> Tuple[np.ndarray, np.ndarray]:
    """Drop missing and non-finite values and return aligned arrays."""
    df = pd.DataFrame({"obs": obs_series, "pred": pred_series})
    df = df.replace([np.inf, -np.inf], np.nan).dropna(axis=0)
    return df["obs"].to_numpy(dtype=np.float64), df["pred"].to_numpy(dtype=np.float64)


def get_timeseries_requests_for_watershed(
    timeseries_cfg: Dict,
    split: str,
    watershed: str,
) -> List[Dict]:
    """Resolve split-specific requests, falling back to watershed defaults."""
    if not isinstance(timeseries_cfg, dict):
        return []

    split_cfg = timeseries_cfg.get(split)
    if isinstance(split_cfg, dict):
        requests = split_cfg.get(watershed, split_cfg.get("__default__", []))
    else:
        requests = timeseries_cfg.get(watershed, timeseries_cfg.get("__default__", []))

    if isinstance(requests, dict):
        return [requests]
    return requests or []


def tail_metrics(obs: np.ndarray, pred: np.ndarray, quantiles: Sequence[float]) -> Dict[str, float]:
    """
    Compute upper-tail diagnostics for non-technical reporting.

    For each quantile q:
      - threshold_qXX: observed threshold at q
      - tail_count_qXX: number of observed points above threshold
      - tail_rmse_qXX: RMSE within observed tail
      - tail_bias_pct_qXX: percent bias of total tail volume
      - predicted_exceedance_rate_qXX: share of predictions above observed threshold
      - observed_exceedance_rate_qXX: share of observations above observed threshold
    """
    out: Dict[str, float] = {}
    if obs.size == 0:
        return out

    for q in quantiles:
        q_int = int(q * 100)
        threshold = float(np.quantile(obs, q))
        mask = obs >= threshold
        count = int(mask.sum())

        out[f"threshold_q{q_int}"] = threshold
        out[f"tail_count_q{q_int}"] = count

        if count == 0:
            out[f"tail_rmse_q{q_int}"] = float("nan")
            out[f"tail_bias_pct_q{q_int}"] = float("nan")
        else:
            obs_tail = obs[mask]
            pred_tail = pred[mask]
            rmse = float(np.sqrt(np.mean((pred_tail - obs_tail) ** 2)))
            obs_sum = float(np.sum(obs_tail))
            pred_sum = float(np.sum(pred_tail))
            bias_pct = float((pred_sum - obs_sum) / obs_sum * 100.0) if obs_sum != 0 else float("nan")
            out[f"tail_rmse_q{q_int}"] = rmse
            out[f"tail_bias_pct_q{q_int}"] = bias_pct

        out[f"predicted_exceedance_rate_q{q_int}"] = float(np.mean(pred >= threshold))
        out[f"observed_exceedance_rate_q{q_int}"] = float(np.mean(obs >= threshold))

    return out


def distribution_summary(obs: np.ndarray, pred: np.ndarray) -> Dict[str, float]:
    """Return compact distribution and tail summary metrics."""
    summary = {
        "n_samples": int(obs.size),
        "obs_mean": float(np.mean(obs)) if obs.size else float("nan"),
        "pred_mean": float(np.mean(pred)) if pred.size else float("nan"),
        "obs_median": float(np.median(obs)) if obs.size else float("nan"),
        "pred_median": float(np.median(pred)) if pred.size else float("nan"),
        "obs_p90": float(np.quantile(obs, 0.90)) if obs.size else float("nan"),
        "pred_p90": float(np.quantile(pred, 0.90)) if pred.size else float("nan"),
        "obs_p95": float(np.quantile(obs, 0.95)) if obs.size else float("nan"),
        "pred_p95": float(np.quantile(pred, 0.95)) if pred.size else float("nan"),
        "obs_p99": float(np.quantile(obs, 0.99)) if obs.size else float("nan"),
        "pred_p99": float(np.quantile(pred, 0.99)) if pred.size else float("nan"),
    }
    summary.update(tail_metrics(obs, pred, quantiles=(0.90, 0.95, 0.99)))
    return summary


def plot_frequency_dashboard(obs: np.ndarray, pred: np.ndarray, title_prefix: str, output_path: str):
    """Create a 4-panel frequency analysis figure with explicit tail diagnostics."""
    if obs.size == 0 or pred.size == 0:
        return

    fig, axes = plt.subplots(2, 2, figsize=(13, 9), dpi=140)
    ax_hist, ax_cdf, ax_exc, ax_qq = axes.flatten()

    min_val = float(min(np.min(obs), np.min(pred)))
    max_val = float(max(np.max(obs), np.max(pred)))
    if min_val == max_val:
        max_val = min_val + 1.0
    bins = np.linspace(min_val, max_val, 45)

    # Histogram on log-y to make rare high-flow differences visible.
    ax_hist.hist(obs, bins=bins, density=True, alpha=0.55, label="Observed", color="#1f77b4")
    ax_hist.hist(pred, bins=bins, density=True, alpha=0.50, label="Predicted", color="#d62728")
    ax_hist.set_yscale("log")
    ax_hist.set_title("Distribution (Density, Log Y)")
    ax_hist.set_xlabel("Streamflow")
    ax_hist.set_ylabel("Density")
    ax_hist.grid(True, alpha=0.25)
    ax_hist.legend(loc="best")

    obs_x, obs_cdf = empirical_cdf(obs)
    pred_x, pred_cdf = empirical_cdf(pred)
    ax_cdf.plot(obs_x, obs_cdf, label="Observed", color="#1f77b4", linewidth=2)
    ax_cdf.plot(pred_x, pred_cdf, label="Predicted", color="#d62728", linewidth=2)
    ax_cdf.set_title("Cumulative Distribution (CDF)")
    ax_cdf.set_xlabel("Streamflow")
    ax_cdf.set_ylabel("Cumulative probability")
    ax_cdf.grid(True, alpha=0.25)
    ax_cdf.legend(loc="best")

    obs_e_x, obs_ex = exceedance_curve(obs)
    pred_e_x, pred_ex = exceedance_curve(pred)
    ax_exc.plot(obs_e_x, obs_ex, label="Observed", color="#1f77b4", linewidth=2)
    ax_exc.plot(pred_e_x, pred_ex, label="Predicted", color="#d62728", linewidth=2)
    ax_exc.set_yscale("log")
    ax_exc.set_title("Exceedance Probability (Upper Tail Focus)")
    ax_exc.set_xlabel("Streamflow threshold")
    ax_exc.set_ylabel("P(X >= threshold)")
    ax_exc.grid(True, alpha=0.25)
    ax_exc.legend(loc="best")

	# Panel 4: Scatter plot of Q-Q plot
    # q = np.linspace(0.01, 0.99, 99)
    # obs_q = np.quantile(obs, q)
    # pred_q = np.quantile(pred, q)
    # qq_min = float(min(np.min(obs_q), np.min(pred_q)))
    # qq_max = float(max(np.max(obs_q), np.max(pred_q)))
    # ax_qq.scatter(obs_q, pred_q, s=16, alpha=0.7, color="#2ca02c", label="Quantiles")
    # ax_qq.plot([qq_min, qq_max], [qq_min, qq_max], "k--", linewidth=1.3, label="1:1 line")
    # ax_qq.set_title("Q-Q Plot")
    # ax_qq.set_xlabel("Observed quantiles")
    # ax_qq.set_ylabel("Predicted quantiles")
    # ax_qq.grid(True, alpha=0.25)
    # ax_qq.legend(loc="best")

    # Panel 4: Scatter plot of observed vs predicted with 1:1 reference.
    scatter_min = float(min(np.min(obs), np.min(pred)))
    scatter_max = float(max(np.max(obs), np.max(pred)))
    ax_qq.scatter(obs, pred, s=12, alpha=0.5, color="#2ca02c", label="Samples")
    ax_qq.plot([scatter_min, scatter_max], [scatter_min, scatter_max], "k--", linewidth=1.3, label="1:1 line")
    ax_qq.set_title("Observed vs Predicted (Scatter)")
    ax_qq.set_xlabel("Observed streamflow")
    ax_qq.set_ylabel("Predicted streamflow")
    ax_qq.grid(True, alpha=0.25)
    ax_qq.legend(loc="best")

    p95_obs = float(np.quantile(obs, 0.95))
    obs_exceed_rate = float(np.mean(obs >= p95_obs))
    pred_exceed_rate = float(np.mean(pred >= p95_obs))
    tail_gap = pred_exceed_rate - obs_exceed_rate
    fig.suptitle(
        f"{title_prefix}\n"
        f"Tail check at observed P95 threshold: observed exceedance={obs_exceed_rate:.3f}, "
        f"predicted exceedance={pred_exceed_rate:.3f}, gap={tail_gap:+.3f}",
        fontsize=12,
    )

    plt.tight_layout(rect=(0, 0, 1, 0.94))
    ensure_dir(os.path.dirname(output_path))
    plt.savefig(output_path)
    plt.close(fig)


def run_frequency_analysis_for_reconstruction(
    recon_df: pd.DataFrame,
    split: str,
    watershed: str,
    method: str,
    target_names: Sequence[str],
    output_dir: str,
    min_samples: int,
) -> pd.DataFrame:
    """
    Analyze reconstructed time-series distributions and save plots/tables.

    This function is designed for stakeholder reporting. It produces:
    - one frequency dashboard plot per scenario and target
    - one summary table with central and tail-focused metrics
    """
    if recon_df.empty:
        return pd.DataFrame()

    working = recon_df.copy()
    if "scenario" not in working.columns:
        working["scenario"] = "all"

    all_rows: List[Dict[str, Union[str, int, float]]] = []
    scenarios = sorted(working["scenario"].dropna().unique().tolist())
    if not scenarios:
        scenarios = ["all"]

    for scenario in scenarios:
        scenario_df = working[working["scenario"] == scenario].copy()
        if scenario_df.empty:
            continue

        scenario_dir = os.path.join(output_dir, split, sanitize_name(watershed), sanitize_name(str(scenario)), method)
        ensure_dir(scenario_dir)

        for target_name in target_names:
            obs_col = f"obs_{target_name}"
            pred_col = f"pred_{target_name}"
            if obs_col not in scenario_df.columns or pred_col not in scenario_df.columns:
                continue

            obs, pred = clean_pair(scenario_df[obs_col], scenario_df[pred_col])
            if obs.size < min_samples:
                continue

            title = f"{watershed} | {scenario} | {split} | reconstruction={method} | target={target_name}"
            plot_path = os.path.join(scenario_dir, f"{target_name}_frequency_distribution.png")
            plot_frequency_dashboard(obs, pred, title, plot_path)

            row: Dict[str, Union[str, int, float]] = {
                "split": split,
                "watershed": watershed,
                "scenario": str(scenario),
                "reconstruction_method": method,
                "target": target_name,
                "plot_path": os.path.relpath(plot_path, output_dir),
            }
            row.update(distribution_summary(obs, pred))
            all_rows.append(row)

    if not all_rows:
        return pd.DataFrame()

    summary_df = pd.DataFrame(all_rows).sort_values(
        ["split", "watershed", "scenario", "reconstruction_method", "target"]
    )
    return summary_df


def basic_metrics(pred: np.ndarray, obs: np.ndarray) -> Dict[str, float]:
    return calculate_hydrology_metrics(pred, obs)


def compute_metrics(df: pd.DataFrame, target_names: Sequence[str]) -> Dict[str, Dict[str, float]]:
    metrics = {}
    flat_preds = []
    flat_obs = []
    for name in target_names:
        pred_col = f"pred_{name}"
        obs_col = f"obs_{name}"
        if pred_col not in df.columns or obs_col not in df.columns:
            continue
        preds = df[pred_col].to_numpy()
        obs = df[obs_col].to_numpy()
        metrics[name] = basic_metrics(preds, obs)
        flat_preds.append(preds)
        flat_obs.append(obs)

    if flat_preds:
        stacked_preds = np.concatenate(flat_preds)
        stacked_obs = np.concatenate(flat_obs)
        metrics["overall"] = basic_metrics(stacked_preds, stacked_obs)
    return metrics


def save_metrics(metrics: Dict, path: str):
    ensure_dir(os.path.dirname(path))
    with open(path, "w") as f:
        json.dump(metrics, f, indent=2)


def plot_window_series(
    df: pd.DataFrame,
    watershed: str,
    window_index: int,
    target_names: Sequence[str],
    output_path: str,
):
    """
    Plot time series for a specific window.
    
    Args:
        df: DataFrame with windowed data for the watershed.
        watershed: Watershed name for plot title.
        window_index: Relative window index (0-based within this watershed).
        target_names: List of target variable names.
        output_path: Path to save the plot.
    """
    # Get unique window indices for this watershed and sort them
    unique_windows = sorted(df["window_index"].unique())
    
    # Map relative window_index to actual global window_index
    if window_index < 0 or window_index >= len(unique_windows):
        print(f"Warning: Window {window_index} out of range for {watershed} (has {len(unique_windows)} windows)")
        return
    
    actual_window_index = unique_windows[window_index]
    subset = df[df["window_index"] == actual_window_index].sort_values("timestep")
    
    if subset.empty:
        print(f"Warning: No samples for {watershed} window {window_index} (global index {actual_window_index})")
        return

    plt.figure(figsize=(10, 4))
    for name in target_names:
        pred_col = f"pred_{name}"
        obs_col = f"obs_{name}"
        if pred_col not in subset.columns or obs_col not in subset.columns:
            continue
        plt.plot(subset["timestamp"], subset[obs_col], label=f"Observed {name}", linestyle="--")
        plt.plot(subset["timestamp"], subset[pred_col], label=f"Predicted {name}")

    plt.title(f"{watershed} - Window {window_index} (global index: {actual_window_index})")
    plt.xlabel("Timestamp")
    plt.ylabel("Value")
    plt.legend()
    plt.tight_layout()
    ensure_dir(os.path.dirname(output_path))
    plt.savefig(output_path)
    plt.close()


def plot_reconstruction_series(
    df: pd.DataFrame,
    watershed: str,
    method: str,
    target_names: Sequence[str],
    output_path: str,
    start: Optional[pd.Timestamp] = None,
    end: Optional[pd.Timestamp] = None,
):
    subset = df.sort_values("timestamp")
    if start is not None:
        subset = subset[subset["timestamp"] >= start]
    if end is not None:
        subset = subset[subset["timestamp"] <= end]

    if subset.empty:
        print(f"Warning: No samples for {watershed} reconstruction plot ({method}) in requested range.")
        return

    plt.figure(figsize=(12, 4))
    for name in target_names:
        pred_col = f"pred_{name}"
        obs_col = f"obs_{name}"
        if pred_col not in subset.columns or obs_col not in subset.columns:
            continue
        plt.plot(subset["timestamp"], subset[obs_col], label=f"Observed {name}", linestyle="--")
        plt.plot(subset["timestamp"], subset[pred_col], label=f"Predicted {name}")

    plt.title(f"{watershed} - Reconstruction ({method})")
    plt.xlabel("Timestamp")
    plt.ylabel("Value")
    plt.legend()
    plt.tight_layout()
    ensure_dir(os.path.dirname(output_path))
    plt.savefig(output_path)
    plt.close()


def parse_args():
    parser = argparse.ArgumentParser(description="Analyze global inference outputs.")
    parser.add_argument("--config", type=str, default="config_global.yaml", help="Path to configuration file.")
    parser.add_argument(
        "--experiment",
        type=str,
        default="streamflow_global_exp1_inference",
        help="Inference experiment entry to use from the config file.",
    )
    parser.add_argument("--source-experiment", type=str, default=None, help="Override source experiment directory.")
    parser.add_argument("--results-subdir", type=str, default=None, help="Override results sub-directory.")
    parser.add_argument("--checkpoint-file", type=str, default=None, help="Checkpoint filename to infer results folder.")
    parser.add_argument(
        "--checkpoint-choice",
        type=str,
        default=None,
        help="If multiple checkpoints are defined, pick which one to analyze.",
    )
    parser.add_argument(
        "--split",
        type=str,
        default=None,
        choices=["train", "val", "test", "all"],
        help="Dataset split to analyze (train/val/test/all).",
    )
    parser.add_argument(
        "--reconstruction-methods",
        type=str,
        nargs="+",
        default=None,
        help="Subset of reconstruction methods to analyze.",
    )
    parser.add_argument(
        "--disable-frequency-analysis",
        action="store_true",
        help="Disable frequency distribution analysis for reconstructed time series.",
    )
    parser.add_argument(
        "--frequency-min-samples",
        type=int,
        default=100,
        help="Minimum valid samples required per scenario/target to generate frequency plots.",
    )
    parser.add_argument(
        "--frequency-output",
        type=str,
        default=None,
        help="Output subdirectory for frequency artifacts (default: frequency_analysis).",
    )
    return parser.parse_args()


def main():
    args = parse_args()
    config, exp_name, full_config = get_experiment_config(args.config, args.experiment)
    print(f"Analyzing inference experiment: {exp_name}")

    source_experiment = args.source_experiment or config.get("source_experiment") or config.get("source_experiment_name")
    if not source_experiment:
        raise ValueError("source_experiment must be specified for analysis.")
    source_config = full_config.get(source_experiment)
    if source_config is None:
        raise ValueError(f"source_experiment '{source_experiment}' not found in {args.config}.")

    combined_config: Dict = {}
    combined_config.update(source_config)
    combined_config.update(config)

    checkpoint_spec = args.checkpoint_file or config.get("checkpoint_files") or config.get("checkpoint_file")
    checkpoint_choice = args.checkpoint_choice or config.get("checkpoint_choice")
    checkpoint_name = None

    if args.checkpoint_file:
        checkpoint_name = args.checkpoint_file
    elif isinstance(checkpoint_spec, dict):
        choice = checkpoint_choice or "best"
        checkpoint_name = checkpoint_spec.get(choice)
        if checkpoint_name is None:
            raise ValueError(f"Checkpoint choice '{choice}' not found in checkpoint_files.")
    elif isinstance(checkpoint_spec, str):
        checkpoint_name = checkpoint_spec
    else:
        checkpoint_name = "best_model.pth"

    derived_subdir = f"{Path(checkpoint_name).stem}_results"
    results_subdir = args.results_subdir or config.get("results_subdir") or derived_subdir

    results_dir = os.path.join(combined_config["save_dir"], source_experiment, results_subdir)
    if not os.path.exists(results_dir):
        raise FileNotFoundError(f"Results directory not found: {results_dir}")

    manifest = load_manifest(results_dir)
    file_format = manifest.get("window_file_format", config.get("window_file_format", "csv"))
    target_names = manifest.get("target_names", combined_config["target_cols"])

    def normalize_splits(value: Optional[Union[str, Sequence[str]]]) -> List[str]:
        if value is None:
            return []
        if isinstance(value, str):
            return [value]
        return list(value)

    def configured_timeseries_splits() -> List[str]:
        timeseries_cfg = config.get("timeseries_plots", {})
        if not isinstance(timeseries_cfg, dict):
            return []
        return [split for split in ("train", "val", "test") if split in timeseries_cfg]

    manifest_splits = manifest.get("requested_splits") or manifest.get("splits")
    split_arg = args.split
    config_split = config.get("split")
    dataset_choice_manifest = manifest.get("dataset_choice")

    if split_arg == "all":
        splits_to_analyze = manifest_splits or ["train", "val", "test"]
    elif split_arg:
        splits_to_analyze = [split_arg]
    else:
        splits_to_analyze = configured_timeseries_splits() or normalize_splits(config_split)
        if not splits_to_analyze:
            splits_to_analyze = normalize_splits(dataset_choice_manifest)
        if not splits_to_analyze:
            splits_to_analyze = manifest_splits or ["test"]

    reconstruction_methods = (
        args.reconstruction_methods
        or config.get("reconstruction_methods")
        or manifest.get("reconstruction_methods")
        or ["average", "latest"]
    )
    reconstruction_methods = [method.lower() for method in reconstruction_methods]
    reconstruction_methods = list(dict.fromkeys(reconstruction_methods))

    metrics_subdir = config.get("metrics_output", "analysis_results")
    analysis_dir = os.path.join(results_dir, metrics_subdir)
    ensure_dir(analysis_dir)
    frequency_output = args.frequency_output or config.get("frequency_output", "frequency_analysis")
    frequency_dir = os.path.join(analysis_dir, frequency_output)
    if not args.disable_frequency_analysis:
        ensure_dir(frequency_dir)

    window_plot_cfg: Dict[str, List[int]] = config.get("window_plots", {})
    timeseries_cfg: Dict[str, List[Dict]] = config.get("timeseries_plots", {})

    summary_metrics: Dict[str, Dict] = {}
    frequency_rows_all: List[pd.DataFrame] = []

    for split in splits_to_analyze:
        split_summary = {"windowed": {}, "reconstructed": {}}
        summary_metrics[split] = split_summary

        split_analysis_dir = os.path.join(analysis_dir, split)
        split_plots_dir = os.path.join(split_analysis_dir, "plots")
        window_plot_dir = os.path.join(split_plots_dir, "windows")
        timeseries_plot_dir = os.path.join(split_plots_dir, "reconstructions")
        ensure_dir(split_analysis_dir)
        ensure_dir(split_plots_dir)

        manifest_watersheds = manifest.get("watersheds_by_split", {}).get(split, [])
        config_watersheds = combined_config.get("watersheds")
        watersheds = manifest_watersheds or config_watersheds or []
        if not watersheds:
            suffix = f"_{split}_windowed_timeseries.{file_format}"
            watersheds = [
                f.replace(suffix, "")
                for f in os.listdir(results_dir)
                if f.endswith(suffix)
            ]

        if not watersheds:
            print(f"No watershed files found to analyze for split '{split}'. Skipping.")
            continue

        for watershed in watersheds:
            ws_key = sanitize_name(watershed)
            window_file = os.path.join(results_dir, f"{ws_key}_{split}_windowed_timeseries.{file_format}")
            window_df = load_dataframe(window_file, file_format)
            if window_df.empty:
                print(f"Skipping {watershed}: windowed data unavailable for split '{split}'.")
                continue

            window_metrics = compute_metrics(window_df, target_names)
            split_summary["windowed"][watershed] = window_metrics
            save_metrics(
                window_metrics,
                os.path.join(split_analysis_dir, f"{ws_key}_{split}_windowed_metrics.json"),
            )

            window_indices = window_plot_cfg.get(watershed, [])
            if isinstance(window_indices, dict):
                window_indices = window_indices.get("windows", [])
            for idx in window_indices:
                plot_window_series(
                    window_df,
                    watershed,
                    int(idx),
                    target_names,
                    os.path.join(window_plot_dir, f"{ws_key}_window_{idx}.png"),
                )

            recon_dfs: Dict[str, pd.DataFrame] = {}
            for method in reconstruction_methods:
                recon_file = os.path.join(results_dir, f"{ws_key}_{split}_reconstructed_{method}.{file_format}")
                recon_df = load_dataframe(recon_file, file_format)
                if recon_df.empty:
                    print(f"Skipping {watershed} reconstruction ({method}) for split '{split}': file missing or empty.")
                    continue

                recon_dfs[method] = recon_df
                recon_metrics = compute_metrics(recon_df, target_names)
                split_summary["reconstructed"].setdefault(method, {})[watershed] = recon_metrics
                save_metrics(
                    recon_metrics,
                    os.path.join(split_analysis_dir, f"{ws_key}_{split}_reconstructed_{method}_metrics.json"),
                )

                if not args.disable_frequency_analysis:
                    frequency_df = run_frequency_analysis_for_reconstruction(
                        recon_df=recon_df,
                        split=split,
                        watershed=watershed,
                        method=method,
                        target_names=target_names,
                        output_dir=frequency_dir,
                        min_samples=args.frequency_min_samples,
                    )
                    if not frequency_df.empty:
                        frequency_rows_all.append(frequency_df)

            plot_requests = get_timeseries_requests_for_watershed(
                timeseries_cfg,
                split,
                watershed,
            )

            for idx, request in enumerate(plot_requests):
                request_methods = request.get("method")
                if request_methods is None:
                    methods_to_plot = reconstruction_methods
                elif isinstance(request_methods, str):
                    methods_to_plot = [request_methods]
                else:
                    methods_to_plot = list(request_methods)
                methods_to_plot = [m.lower() for m in methods_to_plot]

                start = pd.to_datetime(request.get("start")) if request.get("start") else None
                end = pd.to_datetime(request.get("end")) if request.get("end") else None

                for method in methods_to_plot:
                    recon_df = recon_dfs.get(method)
                    if recon_df is None:
                        print(
                            f"Skipping timeseries plot for {watershed} method '{method}' on split '{split}': data unavailable."
                        )
                        continue
                    plot_reconstruction_series(
                        recon_df,
                        watershed,
                        method,
                        target_names,
                        os.path.join(timeseries_plot_dir, f"{ws_key}_{method}_range_{idx}.png"),
                        start=start,
                        end=end,
                    )

        save_metrics(split_summary, os.path.join(split_analysis_dir, "summary_metrics.json"))

    save_metrics(summary_metrics, os.path.join(analysis_dir, "summary_metrics_all_splits.json"))

    if not args.disable_frequency_analysis:
        if frequency_rows_all:
            combined_frequency = pd.concat(frequency_rows_all, ignore_index=True).sort_values(
                ["split", "watershed", "scenario", "reconstruction_method", "target"]
            )
            combined_frequency.to_csv(os.path.join(frequency_dir, "frequency_summary.csv"), index=False)
            with open(os.path.join(frequency_dir, "frequency_summary.json"), "w") as f:
                json.dump(combined_frequency.to_dict(orient="records"), f, indent=2)
        else:
            print("Frequency analysis did not generate outputs (possibly due to missing columns or low sample counts).")

    print(f"\nAnalysis complete. Reports and plots saved to {analysis_dir}")


if __name__ == "__main__":
    main()
